FROM node:18.12.0 AS builder

### Copy Vue.js code
WORKDIR /app
COPY webui webui

WORKDIR /app 
COPY node_modules node_modules

### Build Vue.js into plain HTML/CSS/JS
WORKDIR /app/webui
RUN yarn run build-prod

### Create final container
FROM nginx:stable

### Copy the (built) app from the builder image
COPY --from=builder /app/webui/dist /usr/share/nginx/html