package database

var sql_USERTABLE = `CREATE TABLE IF NOT EXISTS User(
  userID INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  pfpPath TEXT DEFAULT NULL
  );`

var sql_GLOBALCONVOTABLE = `CREATE TABLE IF NOT EXISTS GlobalConversation (
  globalConvoID INTEGER PRIMARY KEY AUTOINCREMENT, 
  isGroup BOOLEAN DEFAULT FALSE,
  groupName TEXT DEFAULT NULL,
  photoPath TEXT DEFAULT NULL
  );`

// CONTROLLA DELBYUSER
var sql_CONVOTABLE = `CREATE TABLE IF NOT EXISTS Conversation (
  userID INTEGER NOT NULL,
  destUserID INTEGER,
  globalConvoID INTEGER NOT NULL,
  lastMsgID INTEGER,
  delByUser BOOLEAN DEFAULT FALSE, 
  visible BOOLEAN DEFAULT TRUE,

  CONSTRAINT fk_user FOREIGN KEY (userID) REFERENCES User(userID),
  CONSTRAINT fk_global FOREIGN KEY (globalConvoID) REFERENCES GlobalConversation(globalConvoID),
  CONSTRAINT fk_dest FOREIGN KEY (destUserID) REFERENCES User(userID),
  
  UNIQUE (userID, globalConvoID)

  );`

var sql_GROUPMEMBERTABLE = `CREATE TABLE IF NOT EXISTS GroupMember (
  groupID INTEGER NOT NULL,
  userID INTEGER NOT NULL,

  CONSTRAINT fk_group FOREIGN KEY (groupID) REFERENCES GlobalConversation(globalConvoID),
  CONSTRAINT fk_user FOREIGN KEY (userID) REFERENCES User(userID),

  UNIQUE (groupID, userID)
  );`

var sql_MSGTABLE = `CREATE TABLE IF NOT EXISTS Message (
  msgID INTEGER PRIMARY KEY AUTOINCREMENT,
  convoID NOT NULL,
  senderID NOT NULL,
  content TEXT NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  isPhoto INTEGER DEFAULT 0,
  CONSTRAINT fk_convo FOREIGN KEY (convoID) REFERENCES GlobalConversation(globalConvoID),
  CONSTRAINT fk_user FOREIGN KEY (senderID) REFERENCES User(userID),
  
  UNIQUE (msgID, convoID)
);`

var sql_COMMTABLE = `CREATE TABLE IF NOT EXISTS Comment (
  commID INTEGER PRIMARY KEY AUTOINCREMENT,
  msgID NOT NULL,
  senderID NOT NULL,
  emoji TEXT NOT NULL,
  
  CONSTRAINT fk_convo FOREIGN KEY (msgID) REFERENCES Message(mssgID),
  CONSTRAINT fk_user FOREIGN KEY (senderID) REFERENCES User(userID),
  
  UNIQUE (commID, msgID)
);`

var sql_CHECKMARKSTABLE = `CREATE TABLE IF NOT EXISTS Checkmarks (
  msgID INTEGER NOT NULL,
  sent BOOLEAN DEFAULT FALSE,
  sentTime DATETIME DEFAULT CURRENT_TIMESTAMP,
  read BOOLEAN DEFAULT FALSE,
  readTime DATETIME DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_message FOREIGN KEY (msgID) REFERENCES Message(msgID)
  );`
