package database

var sql_USERTABLE = `CREATE TABLE IF NOT EXISTS User(
  userID INTEGER NOT NULL UNIQUE,
  username TEXT NOT NULL UNIQUE,
  PRIMARY KEY(userID)
  );`

var sql_CONVOTABLE = `CREATE TABLE IF NOT EXISTS Conversation (
  convoID INTEGER NOT NULL, 
  sendID INTEGER NOT NULL,
  recID INTEGER NOT NULL,
  groupID INTEGER,
  lastMsgId INTEGER,
  delBySend BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (convoID, sendID),
  CONSTRAINT fk_convo
    FOREIGN KEY (sendID) REFERENCES User(userID),
    FOREIGN KEY (recID) REFERENCES User(userID)
    FOREIGN KEY (groupID) REFERENCES Group(groupID)
  UNIQUE (convoID, sendID, groupID)
  );`

var sql_MSGTABLE = `CREATE TABLE IF NOT EXISTS Message (
  msgID INTEGER NOT NULL UNIQUE,
  convoID NOT NULL,
  sendID NOT NULL,
  content TEXT NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (msgID, convoID, sendID),
  CONSTRAINT fk_msg
    FOREIGN KEY (sendID) REFERENCES User(userID),
    FOREIGN KEY (convoID) REFERENCES Conversation(convoID)
      ON DELETE CASCADE  
);`   

var sql_COMMTABLE = `CREATE TABLE IF NOT EXISTS Comment (
  commID INTEGER NOT NULL UNIQUE,
  msgID NOT NULL,
  sendID NOT NULL,
  emoji TEXT NOT NULL,
  PRIMARY KEY (commID, msgID),
  CONSTRAINT fk_comm
    FOREIGN KEY (msgID) REFERENCES Message(msgID)
      ON DELETE CASCADE,
    FOREIGN KEY (sendID) REFERENCES User(userID)    
  );`

var sql_GROUPTABLE = `CREATE TABLE IF NOT EXISTS Group (
  groupID INTEGER NOT NULL UNIQUE,
  ownerID INTEGER NOT NULL,
  name TEXT NOT NULL,
  PRIMARY KEY (groupID),
  CONSTRAINT fk_group_owner
    FOREIGN KEY (ownerID) REFERENCES User(userID),
  );`

var sql_MEMBERTABLE = `CREATE TABLE IF NOT EXISTS GroupMember (
  groupID INTEGER NOT NULL,
  memberID INTEGER NOT NULL,
  PRIMARY KEY (groupID, memberID),
  CONSTRAINT fk_group_member
    FOREIGN KEY (groupID) REFERENCES Group(groupID)
      ON DELETE CASCADE,
    FOREIGN KEY (memberID) REFERENCES User(userID)
      ON DELETE CASCADE
  );`
